---
- name: Install Docker
  hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        update_cache: true

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Get Ubuntu version
      ansible.builtin.command: "lsb_release -cs"
      register: ubuntu_version
      changed_when: true

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present

    - name: Update APT Cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin
        update_cache: true

    # add the current user to the docker group
    - name: Add user permissions
      ansible.builtin.command: "usermod -aG docker {{ ansible_env.SUDO_USER }}"
      changed_when: true
